-- Optional middle ground: put joins and logic in a view,
-- then point a RelationalTable extract at it.
USE ROLE SYSADMIN;
CREATE OR REPLACE VIEW FDH_DEMO.SAMPLE.V_JEDOX_ACTUALS_BY_GROUP AS
SELECT f.VERSION, f.PERIOD, f.COST_CENTER, c.PARENT AS COST_CENTER_GROUP, f.ACCOUNT, SUM(f.AMOUNT) AS AMOUNT
FROM FDH_DEMO.SAMPLE.FACT_ACTUALS f
JOIN FDH_DEMO.SAMPLE.DIM_COST_CENTER c ON c.COST_CENTER = f.COST_CENTER
WHERE f.VERSION = 'Actual'
GROUP BY f.VERSION, f.PERIOD, f.COST_CENTER, c.PARENT, f.ACCOUNT;

GRANT SELECT ON VIEW FDH_DEMO.SAMPLE.V_JEDOX_ACTUALS_BY_GROUP TO ROLE JEDOX_ETL_ROLE;
